CREATE
OR REPLACE TRIGGER TR_AUDIT_CARD_UPDATE
BEFORE UPDATE ON CARD
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_CARD(
        AUDIT_TYPE,
        CARD_ID,
        DECK_ID,
        YOUTUBE_VIDEO_ID,
        TITLE,
        ARTIST,
        RELEASE_YEAR,
        CATEGORY_ID
    )
    VALUES (
        'UPDATE',
        OLD.ID,
        OLD.DECK_ID,
        OLD.YOUTUBE_VIDEO_ID,
        OLD.TITLE,
        OLD.ARTIST,
        OLD.RELEASE_YEAR,
        OLD.CATEGORY_ID
    );
END;
