CREATE TABLE IF NOT EXISTS AUDIT_CARD(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    AUDIT_TYPE ENUM('UPDATE', 'DELETE') NOT NULL,
    CARD_ID UUID NOT NULL,
    DECK_ID UUID NOT NULL,
    YOUTUBE_VIDEO_ID VARCHAR(32) NULL,
    TITLE VARCHAR(510) NOT NULL,
    ARTIST VARCHAR(510) NOT NULL,
    RELEASE_YEAR INT NULL,
    CATEGORY_ID UUID NULL,
    PRIMARY KEY(ID)
);
