-- The one card in play, at most one row per game. RELEASE_YEAR is snapshotted
-- here as the round's answer; it must not be sent to any client until the game
-- reaches ROUND_PHASE 'reveal'.
CREATE TABLE IF NOT EXISTS TRACK_TIMELINE_CURRENT_CARD(
    ID UUID NOT NULL DEFAULT UUID(),
    TRACK_TIMELINE_GAME_ID UUID NOT NULL,
    CARD_ID UUID NOT NULL,
    RELEASE_YEAR INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(TRACK_TIMELINE_GAME_ID) REFERENCES TRACK_TIMELINE_GAME(ID) ON DELETE CASCADE,
    FOREIGN KEY(CARD_ID) REFERENCES CARD(ID) ON DELETE CASCADE,
    CONSTRAINT GAME_UNIQUE UNIQUE(TRACK_TIMELINE_GAME_ID)
);
