-- One player's vote on a challenge. The unique constraint is what makes it one
-- vote each: a vote cannot be changed or repeated once cast.
CREATE TABLE IF NOT EXISTS TRACK_TIMELINE_CHALLENGE_VOTE(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CHALLENGE_ID UUID NOT NULL,
    PLAYER_ID UUID NOT NULL,
    AGREE BOOLEAN NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(CHALLENGE_ID) REFERENCES TRACK_TIMELINE_CHALLENGE(ID) ON DELETE CASCADE,
    FOREIGN KEY(PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE,
    CONSTRAINT CHALLENGE_PLAYER_UNIQUE UNIQUE(CHALLENGE_ID, PLAYER_ID)
);
