-- Append-only log of completed games. No foreign keys, for the same reason as
-- TRACK_TIMELINE_LOG_PLACEMENT.
CREATE TABLE IF NOT EXISTS TRACK_TIMELINE_LOG_WIN(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    USER_ID UUID NOT NULL,
    CARDS_TO_WIN INT NOT NULL,
    PLAYER_COUNT INT NOT NULL,
    PRIMARY KEY(ID)
);
