-- Cards a player has won, ordered by POSITION (0 is earliest). RELEASE_YEAR is
-- snapshotted at placement time. Unlike the card in play, these years ARE public
-- to everyone: they are the board state every placement decision reasons about.
CREATE TABLE IF NOT EXISTS TRACK_TIMELINE_PLAYER_TIMELINE(
    ID UUID NOT NULL DEFAULT UUID(),
    TRACK_TIMELINE_GAME_ID UUID NOT NULL,
    PLAYER_ID UUID NOT NULL,
    CARD_ID UUID NOT NULL,
    RELEASE_YEAR INT NOT NULL,
    POSITION INT NOT NULL,
    PLACED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY(ID),
    FOREIGN KEY(TRACK_TIMELINE_GAME_ID) REFERENCES TRACK_TIMELINE_GAME(ID) ON DELETE CASCADE,
    FOREIGN KEY(PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE,
    FOREIGN KEY(CARD_ID) REFERENCES CARD(ID) ON DELETE CASCADE,
    CONSTRAINT GAME_PLAYER_CARD_UNIQUE UNIQUE(TRACK_TIMELINE_GAME_ID, PLAYER_ID, CARD_ID)
);
