-- One song, one seat per game. IF NOT EXISTS so re-runs after CREATE TABLE
-- already carried GAME_CARD_UNIQUE stay idempotent.
CREATE UNIQUE INDEX IF NOT EXISTS UX_TT_PLAYER_TIMELINE_GAME_CARD
    ON TRACK_TIMELINE_PLAYER_TIMELINE (TRACK_TIMELINE_GAME_ID, CARD_ID);
